/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "MovieKt"

include(
    "build-library",
    "moviekt-animation",
    "moviekt-clips",
    "moviekt-core",
    "moviekt-dsl",
    "moviekt-filter",
    "moviekt-layout",
    "moviekt-theme"
)

